# Generated by Django 4.2.4 on 2023-08-13 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_salutation', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], default='herr', max_length=10)),
                ('reviewer_firstname', models.CharField(max_length=50)),
                ('reviewer_lastname', models.CharField(max_length=50)),
                ('reviewer_email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('reviewer_serviceType', models.CharField(choices=[('privateMoving', 'Privateumzüge'), ('companyMoving', 'Firmenumzüge'), ('houseCleaning', 'Hausreinigung'), ('andere', 'andere')], default='privateMoving', max_length=50, verbose_name='Service')),
                ('reviewer_rating', models.CharField(choices=[('1', '1 (Sehr unzufrieden)'), ('2', '2 (Unzufrieden)'), ('3', '3 (Neutral)'), ('4', '4 (Zufrieden)'), ('5', '5 (Sehr zufrieden)')], default='5', max_length=10, verbose_name='Gesamtbewertung')),
                ('reviewer_content', models.TextField(verbose_name='Schreiben Sie hier unten Ihre Nachricht')),
                ('reviewer_confirmation', models.CharField(choices=[('ja', 'Ja'), ('nein', 'Nein')], default='ja', max_length=10, verbose_name='Dürfen wir Ihre Bewertung auf unserer Website oder Marketingmaterialien veröffentlichen?')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
