# Generated by Django 4.2.4 on 2023-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='reviewer_salutation',
            field=models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('noValue', 'Ohne Angabe')], max_length=10),
        ),
    ]
