# Generated by Django 4.2.4 on 2023-08-13 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customerreview_reviewer_salutation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau')], default='herr', max_length=10)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='Schreiben Sie hier unten Ihre Nachricht')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
