# Generated by Django 4.2.4 on 2023-08-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='data_protection',
            field=models.BooleanField(default=False),
        ),
    ]
