# Generated by Django 4.2.4 on 2023-08-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_contactus_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='data_protection',
            field=models.BooleanField(),
        ),
    ]
